/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class thesiaslib */

#ifndef _Included_thesiaslib
#define _Included_thesiaslib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     thesiaslib
 * Method:    thesiasRun
 * Signature: (Ljava/lang/String;II[IIIIIIIIII[III)I
 */
JNIEXPORT jint JNICALL Java_thesiaslib_thesiasRun
  (JNIEnv *, jobject, jstring, jint, jint, jintArray, jint, jint, jint, jint, jint, jint, jint, jint, jint, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
